import { StyleSheet } from 'react-native';
import { colors } from './theme/colors';

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  appRoot: {
    flex: 1,
    backgroundColor: colors.bg2,
  },
  authRoot: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  authHeader: {
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authHeaderImage: {
    width: '100%',
    height: '100%',
  },
  authBack: {
    position: 'absolute',
    left: 5,
    top: 5,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authForm: {
    flex: 1,
    backgroundColor: colors.bg2,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  authFormContent: {
    padding: 15,
    paddingBottom: 36,
  },
  fieldBlock: {
    marginTop: 5,
  },
  label: {
    color: colors.brown,
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 5,
    marginBottom: 5,
  },
  inputWrap: {
    minHeight: 45,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.white,
    justifyContent: 'center',
  },
  inputWrapTall: {
    minHeight: 82,
  },
  input: {
    color: colors.brown,
    fontSize: 15,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  inputWithIcon: {
    paddingRight: 50,
  },
  inputMultiline: {
    minHeight: 76,
    textAlignVertical: 'top',
  },
  inputIconButton: {
    position: 'absolute',
    right: 5,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputIcon: {
    width: 18,
    height: 18,
    tintColor: colors.brown,
  },
  errorText: {
    color: colors.error,
    fontSize: 15,
    marginHorizontal: 5,
    marginTop: 5,
  },
  statusText: {
    color: colors.orange,
    fontSize: 14,
    fontWeight: '700',
    marginHorizontal: 5,
    marginTop: 5,
  },
  errorTextCentered: {
    color: colors.error,
    fontSize: 15,
    textAlign: 'center',
    marginTop: 5,
  },
  forgotButton: {
    alignSelf: 'flex-end',
    marginTop: 5,
    marginRight: 5,
  },
  linkText: {
    color: colors.brown,
    fontSize: 15,
    fontWeight: '700',
  },
  button: {
    alignSelf: 'center',
    minWidth: 125,
    height: 45,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    marginTop: 15,
  },
  buttonWide: {
    minWidth: 200,
  },
  buttonOutline: {
    backgroundColor: colors.white,
  },
  buttonPressed: {
    opacity: 0.55,
  },
  buttonText: {
    color: colors.brown,
    fontSize: 15,
    fontWeight: '700',
  },
  authDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    marginHorizontal: 5,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.brown,
  },
  dividerText: {
    color: colors.brown,
    fontSize: 12,
    paddingHorizontal: 10,
  },
  rowGap: {
    flexDirection: 'row',
    gap: 10,
  },
  half: {
    flex: 1,
  },
  wideHalf: {
    flex: 1.5,
  },
  segmented: {
    flexDirection: 'row',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.white,
    minHeight: 45,
    overflow: 'hidden',
  },
  segment: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  segmentActive: {
    backgroundColor: colors.bg,
  },
  segmentText: {
    color: colors.brown,
    fontSize: 13,
  },
  segmentTextActive: {
    fontWeight: '700',
  },
  centerLink: {
    alignSelf: 'center',
    marginTop: 5,
  },
  minimalRoot: {
    flex: 1,
    backgroundColor: colors.bg2,
  },
  minimalContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingBottom: 32,
  },
  minimalBack: {
    alignSelf: 'flex-start',
    width: 40,
    height: 40,
    marginTop: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backGlyph: {
    color: colors.brown,
    fontSize: 42,
    lineHeight: 42,
    fontWeight: '600',
  },
  bigTitle: {
    color: colors.brown,
    fontSize: 35,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 20,
  },
  minimalDescription: {
    color: colors.brown,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 22,
  },
  minimalInput: {
    alignSelf: 'stretch',
    marginTop: 15,
  },
  chickenImage: {
    width: 200,
    height: 200,
    marginTop: 20,
  },
  otpTitle: {
    color: colors.brown,
    fontSize: 35,
    fontWeight: '800',
    textAlign: 'center',
  },
  otpDesc: {
    color: colors.orange,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 5,
  },
  otpPrompt: {
    color: colors.brown,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 15,
  },
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    gap: 10,
  },
  otpInput: {
    width: 40,
    height: 60,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.white,
    color: colors.brown,
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  resetTitle: {
    color: colors.brown,
    fontSize: 30,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 15,
  },
  mapRoot: {
    flex: 1,
    backgroundColor: colors.mapLand,
  },
  realMap: {
    flex: 1,
  },
  myLocationMarker: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: colors.orange,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  myLocationAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
  },
  mapMarker: {
    width: 54,
    height: 62,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: colors.brown,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fakeMap: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: colors.mapLand,
    overflow: 'hidden',
  },
  mapWater: {
    position: 'absolute',
    left: -60,
    top: 120,
    width: 260,
    height: 680,
    borderRadius: 120,
    backgroundColor: colors.mapWater,
    transform: [{ rotate: '-16deg' }],
  },
  mapRoad: {
    position: 'absolute',
    height: 26,
    borderRadius: 13,
    backgroundColor: '#F8E8BB',
  },
  mapRoadOne: {
    left: -30,
    right: -30,
    top: 245,
    transform: [{ rotate: '18deg' }],
  },
  mapRoadTwo: {
    left: -50,
    right: -30,
    top: 450,
    transform: [{ rotate: '-24deg' }],
  },
  mapRoadThree: {
    width: 520,
    top: 330,
    right: -120,
    transform: [{ rotate: '82deg' }],
  },
  mapGrid: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderWidth: 18,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  mapPin: {
    position: 'absolute',
    width: 54,
    height: 62,
    borderRadius: 20,
    borderWidth: 3,
    borderColor: colors.brown,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinAvatar: {
    width: 42,
    height: 42,
    borderRadius: 14,
  },
  searchCard: {
    position: 'absolute',
    top: 15,
    left: 16,
    right: 16,
    height: 50,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(178,114,93,0.35)',
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    shadowColor: colors.black,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
    zIndex: 10,
  },
  searchIcon: {
    width: 22,
    height: 22,
    marginRight: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchText: {
    flex: 1,
    color: colors.brown,
    fontSize: 13,
    fontWeight: '700',
  },
  topAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: colors.white,
  },
  bottomNav: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 20,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  navPill: {
    position: 'absolute',
    bottom: 0,
    width: 136,
    height: 44,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 15,
    shadowColor: colors.black,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 5,
  },
  navPillLeft: {
    right: '50%',
    marginRight: 16,
  },
  navPillRight: {
    left: '50%',
    marginLeft: 16,
  },
  navBlob: {
    position: 'absolute',
    bottom: 0,
    width: 130,
    height: 50,
  },
  leftNavIcons: {
    position: 'absolute',
    left: 10,
    bottom: 5,
    flexDirection: 'row',
    gap: 10,
  },
  rightNavIcons: {
    position: 'absolute',
    right: 10,
    bottom: 5,
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconImage: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  navBarIcon: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navBarIconImage: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
    tintColor: colors.brown,
  },
  navBadge: {
    position: 'absolute',
    right: 3,
    top: 3,
    minWidth: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: '#FF0000',
    borderWidth: 1,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  navBadgeText: {
    color: colors.white,
    fontSize: 7,
    lineHeight: 9,
    fontWeight: '800',
  },
  radarButton: {
    position: 'absolute',
    bottom: 6,
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
  },
  radarHalo: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: colors.bg,
    borderWidth: 3,
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  radarImage: {
    width: 49,
    height: 49,
  },
  radarOverlay: {
    position: 'absolute',
    width: 49,
    height: 49,
    left: 4.5,
    top: 4.5,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.22)',
    justifyContent: 'center',
    padding: 20,
  },
  userDialog: {
    backgroundColor: colors.bg2,
    borderRadius: 25,
    padding: 15,
  },
  userDialogTop: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.profile,
    padding: 5,
    marginBottom: 15,
  },
  avatarFrame: {
    borderRadius: 8,
    borderWidth: 3,
    borderColor: colors.brown,
    backgroundColor: colors.profile,
    padding: 3,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  onlineBadge: {
    position: 'absolute',
    right: -3,
    bottom: -3,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.online,
    borderWidth: 2,
    borderColor: colors.bg2,
  },
  dialogNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  dialogName: {
    flex: 1,
    color: colors.brown,
    fontSize: 15,
    fontWeight: '800',
  },
  dialogDistance: {
    color: colors.orange,
    fontSize: 12,
    fontWeight: '800',
  },
  statusTag: {
    alignSelf: 'flex-start',
    marginTop: 5,
    color: colors.brown,
    fontSize: 12,
    fontStyle: 'italic',
    backgroundColor: colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  infoLine: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  infoIcon: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoText: {
    flex: 1,
    marginLeft: 8,
    color: colors.brown,
    fontSize: 12,
  },
  profileRoot: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  profileTopBar: {
    height: 49,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(178,114,93,0.14)',
  },
  profileBackButton: {
    width: 46,
    height: 49,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileBackText: {
    color: colors.brown,
    fontSize: 28,
    lineHeight: 30,
    fontWeight: '700',
  },
  profileHeaderTitle: {
    flex: 1,
    color: colors.brown,
    fontSize: 16,
    fontWeight: '900',
  },
  profileScene: {
    flex: 1,
    backgroundColor: '#BFE1D6',
  },
  profileContent: {
    position: 'relative',
    paddingTop: 35,
    paddingBottom: 28,
    overflow: 'hidden',
  },
  profileLandscape: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    minHeight: 760,
  },
  profileSky: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 265,
    backgroundColor: '#B9DCEC',
  },
  profileLake: {
    position: 'absolute',
    right: -72,
    top: 92,
    width: 240,
    height: 170,
    borderRadius: 90,
    backgroundColor: '#9ACDDA',
    transform: [{ rotate: '-18deg' }],
  },
  profileHillBack: {
    position: 'absolute',
    left: -80,
    right: -80,
    bottom: 170,
    height: 260,
    borderTopLeftRadius: 190,
    borderTopRightRadius: 190,
    backgroundColor: '#D6E58D',
    transform: [{ rotate: '-8deg' }],
  },
  profileHillFront: {
    position: 'absolute',
    left: -70,
    right: -70,
    bottom: -10,
    height: 330,
    borderTopLeftRadius: 210,
    borderTopRightRadius: 210,
    backgroundColor: '#9FCB55',
    transform: [{ rotate: '5deg' }],
  },
  profilePath: {
    position: 'absolute',
    left: '43%',
    bottom: -20,
    width: 70,
    height: 410,
    borderRadius: 45,
    backgroundColor: 'rgba(248,232,187,0.72)',
    transform: [{ rotate: '12deg' }],
  },
  headerBar: {
    height: 56,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBack: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    color: colors.brown,
    fontSize: 20,
    fontWeight: '800',
  },
  headerRight: {
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileLoader: {
    marginTop: 10,
  },
  hangingWrap: {
    marginHorizontal: 34,
    marginTop: 24,
    position: 'relative',
    zIndex: 1,
  },
  hangingWrapCompact: {
    marginTop: 15,
  },
  woodRow: {
    position: 'absolute',
    left: 52,
    right: 52,
    top: -36,
    height: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: -1,
  },
  woodStrip: {
    width: 11,
    height: 44,
  },
  hangingCard: {
    backgroundColor: colors.bg2,
    borderRadius: 6,
    padding: 13,
    shadowColor: colors.black,
    shadowOpacity: 0.09,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    zIndex: 2,
  },
  profileIdentityBox: {
    backgroundColor: colors.profile,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 9,
    minHeight: 96,
  },
  profilePhoto: {
    width: 72,
    height: 72,
    borderRadius: 4,
  },
  profileIdentityText: {
    flex: 1,
    marginLeft: 15,
  },
  profileName: {
    color: colors.brown,
    fontSize: 14,
    fontWeight: '800',
  },
  profileSmall: {
    color: colors.brown,
    fontSize: 10,
    marginTop: 4,
    lineHeight: 14,
  },
  introText: {
    color: colors.brown,
    textAlign: 'center',
    fontSize: 10,
    marginTop: 10,
    lineHeight: 14,
  },
  profilePrimaryAction: {
    alignSelf: 'center',
    minWidth: 180,
    height: 30,
    borderRadius: 5,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.orange,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 9,
    paddingHorizontal: 14,
  },
  profilePrimaryActionSmall: {
    flex: 1,
    height: 34,
    borderRadius: 5,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.orange,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePrimaryActionText: {
    color: colors.brown,
    fontSize: 11,
    fontWeight: '900',
  },
  profileActionRow: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 10,
    paddingHorizontal: 14,
  },
  profileSecondaryAction: {
    flex: 1,
    height: 34,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileSecondaryActionText: {
    color: colors.brown,
    fontSize: 11,
    fontWeight: '900',
  },
  cardTitle: {
    color: colors.brown,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  profileInfoBox: {
    backgroundColor: colors.profile,
    padding: 9,
  },
  profileInfoText: {
    color: colors.brown,
    fontSize: 10,
    lineHeight: 18,
  },
  profileInfoLabel: {
    fontWeight: '800',
  },
  profileSubjectRow: {
    flexDirection: 'row',
    gap: 11,
    marginTop: 12,
    paddingHorizontal: 8,
  },
  profileSubjectCard: {
    flex: 1,
    minHeight: 72,
    backgroundColor: colors.bg2,
    borderRadius: 4,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 6,
  },
  profileSubjectTitle: {
    color: colors.brown,
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 8,
  },
  profileSubjectText: {
    color: colors.brown,
    fontSize: 10,
    lineHeight: 17,
    textAlign: 'center',
  },
  profileTiles: {
    flexDirection: 'row',
    marginHorizontal: 28,
    marginTop: 22,
    gap: 9,
  },
  profileTile: {
    flex: 1,
    height: 75,
    backgroundColor: colors.bg2,
    borderRadius: 6,
    alignItems: 'center',
    paddingTop: 13,
    paddingHorizontal: 4,
    position: 'relative',
    zIndex: 1,
  },
  smallWoodRow: {
    position: 'absolute',
    top: -20,
    left: 13,
    right: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: -1,
  },
  smallWood: {
    width: 10,
    height: 27,
  },
  profileTileText: {
    color: colors.brown,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  profileTileValue: {
    color: colors.orange,
    fontSize: 15,
    fontWeight: '900',
    marginTop: 6,
  },
  profileTileDetail: {
    color: colors.brown,
    fontSize: 9,
    marginTop: 4,
    textAlign: 'center',
  },
  profileBadgeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  profileBadge: {
    flex: 1,
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: colors.bg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 5,
  },
  profileBadgeImage: {
    position: 'absolute',
    width: 86,
    height: 68,
    opacity: 0.5,
  },
  profileBadgeText: {
    color: colors.brown,
    fontSize: 9,
    fontWeight: '900',
    textAlign: 'center',
  },
  notificationRoot: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  notificationTopBand: {
    height: 0,
    backgroundColor: colors.bg,
  },
  notificationHeader: {
    height: 70,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
  },
  notificationBack: {
    width: 27,
    height: 44,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  notificationBackText: {
    color: colors.brown,
    fontSize: 26,
    lineHeight: 28,
    fontWeight: '500',
  },
  notificationTitle: {
    color: colors.brown,
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
    marginLeft: 8,
  },
  notificationScroll: {
    flex: 1,
    backgroundColor: colors.bg2,
  },
  notificationContent: {
    paddingHorizontal: 23,
    paddingBottom: 28,
  },
  notificationLoader: {
    marginTop: 10,
  },
  notificationSection: {
    marginTop: 4,
  },
  notificationSectionTitle: {
    color: colors.brown,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '900',
    marginBottom: 14,
  },
  notificationCard: {
    minHeight: 72,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 12,
    marginBottom: 20,
    shadowColor: colors.brown,
    shadowOpacity: 0.12,
    shadowRadius: 3,
    shadowOffset: { width: 1, height: 2 },
    elevation: 2,
  },
  notificationCardPressed: {
    opacity: 0.72,
  },
  notificationAvatarFrame: {
    width: 50,
    height: 50,
    borderRadius: 8,
    borderWidth: 3,
    borderColor: colors.bg,
    backgroundColor: colors.white,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationAvatar: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  notificationCardBody: {
    flex: 1,
    marginLeft: 13,
    justifyContent: 'center',
  },
  notificationMessage: {
    color: colors.brown,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  notificationTime: {
    color: colors.brown,
    fontSize: 9,
    lineHeight: 12,
    marginTop: 3,
  },
  settingsCard: {
    marginHorizontal: 15,
    marginTop: 10,
    height: 45,
    backgroundColor: colors.bg2,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  settingsIcon: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsText: {
    marginLeft: 5,
    color: colors.brown,
    fontSize: 12,
    fontWeight: '800',
  },
  headerEditIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editAvatarWrap: {
    width: 88,
    height: 88,
  },
  editAvatarIcon: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    right: 0,
    bottom: 0,
    backgroundColor: colors.brown,
    borderWidth: 2,
    borderColor: colors.bg2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addInfoText: {
    color: colors.brown,
    fontSize: 14,
    fontWeight: '800',
    marginTop: 10,
    borderTopWidth: 2,
    borderTopColor: colors.brown,
    paddingTop: 10,
  },
  settingsRoot: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  settingsStatusBand: {
    height: 43,
    backgroundColor: colors.bg,
  },
  settingsHeader: {
    height: 45,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  settingsBackButton: {
    width: 28,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  settingsTitle: {
    color: colors.brown,
    fontSize: 19,
    fontWeight: '900',
    lineHeight: 24,
  },
  settingsMenu: {
    flex: 1,
    backgroundColor: colors.bg2,
    paddingHorizontal: 30,
    paddingTop: 17,
  },
  settingsRow: {
    minHeight: 59,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.bg2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
    marginBottom: 11,
    shadowColor: colors.brownStroke,
    shadowOpacity: 0.7,
    shadowRadius: 0,
    shadowOffset: { width: 2, height: 2 },
    elevation: 2,
  },
  settingsRowText: {
    flex: 1,
    color: colors.brown,
    fontSize: 12,
    lineHeight: 16,
  },
  settingsRowRight: {
    minWidth: 50,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  settingsSwitch: {
    transform: [{ scaleX: 0.75 }, { scaleY: 0.75 }],
  },
  dangerText: {
    color: colors.deleteRed,
    fontWeight: '700',
  },
  modalCard: {
    backgroundColor: colors.bg2,
    borderRadius: 20,
    padding: 18,
    maxHeight: '86%',
  },
  modalTitle: {
    color: colors.brown,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 12,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  subjectGroup: {
    marginBottom: 14,
  },
  subjectGroupTitle: {
    color: colors.brown,
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 8,
  },
  subjectItem: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  subjectName: {
    flex: 1,
    color: colors.brown,
  },
  deleteAction: {
    color: colors.error,
    fontWeight: '800',
  },
  emptyText: {
    color: colors.hint,
    fontSize: 13,
  },
  emptyState: {
    minHeight: 140,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  emptyStateText: {
    color: colors.brown,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  friendsRoot: {
    flex: 1,
    backgroundColor: colors.bg2,
  },
  friendSearch: {
    height: 45,
    marginHorizontal: 15,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  friendSearchInput: {
    flex: 1,
    color: colors.brown,
    fontSize: 15,
  },
  friendList: {
    paddingTop: 4,
    paddingBottom: 15,
  },
  friendItem: {
    marginHorizontal: 15,
    marginVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.profile,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  friendItemCompact: {
    marginHorizontal: 0,
  },
  friendBody: {
    flex: 1,
    marginLeft: 10,
  },
  friendTopLine: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  friendName: {
    flex: 1,
    color: colors.brown,
    fontSize: 15,
    fontWeight: '800',
  },
  friendTime: {
    color: colors.hint,
    fontSize: 12,
  },
  friendLastMessage: {
    color: colors.brown,
    fontSize: 12,
    marginTop: 4,
  },
  friendOptions: {
    alignSelf: 'center',
    backgroundColor: colors.bg2,
    borderRadius: 18,
    padding: 15,
    width: 260,
  },
  optionRow: {
    width: 180,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    marginTop: 6,
  },
  optionText: {
    color: colors.brown,
    fontSize: 13,
  },
  chatRoot: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  plusGlyph: {
    color: colors.brown,
    fontSize: 34,
    fontWeight: '500',
    paddingHorizontal: 12,
  },
  messageList: {
    paddingTop: 10,
    paddingBottom: 10,
  },
  messageRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 6,
    alignItems: 'flex-start',
  },
  messageRowMine: {
    justifyContent: 'flex-end',
  },
  messageBubble: {
    maxWidth: '74%',
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    marginHorizontal: 8,
  },
  messageIncoming: {
    backgroundColor: colors.white,
    borderColor: colors.brownStroke,
  },
  messageMine: {
    backgroundColor: colors.chatSent,
    borderColor: colors.chatSent,
  },
  messageText: {
    color: colors.brown,
    fontSize: 12,
  },
  messageTextMine: {
    color: colors.white,
  },
  inputBar: {
    minHeight: 45,
    marginHorizontal: 15,
    marginTop: 5,
    marginBottom: 15,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.brownStroke,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  stickerGlyph: {
    color: colors.brown,
    fontSize: 20,
  },
  chatInput: {
    flex: 1,
    color: colors.brown,
    fontSize: 15,
    maxHeight: 92,
    marginHorizontal: 8,
  },
  inputGlyph: {
    color: colors.brown,
    fontSize: 18,
    marginRight: 8,
  },
  chatActionIcon: {
    width: 18,
    height: 18,
    tintColor: colors.brown,
    marginRight: 8,
  },
  sendGlyph: {
    color: colors.brown,
    fontSize: 30,
    lineHeight: 34,
  },
  toast: {
    position: 'absolute',
    left: 18,
    right: 18,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: colors.brown,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: colors.black,
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 20,
    zIndex: 999,
  },
  toastError: {
    backgroundColor: colors.error,
  },
  toastSuccess: {
    backgroundColor: colors.orange,
  },
  toastText: {
    color: colors.white,
    fontWeight: '700',
    textAlign: 'center',
  },
});
